### ISSUE TITLE
issues i ran into: recommended usage & prerequesites

### ISSUE THREAD

**Issue by domainController** [samy280497/youtubefetch#1]
Hello,

for following users who want use that script and for me and my short-term memory handling when i come back

if you run into this issue while running kali linux 
![google_api-client_python](https://user-images.githubusercontent.com/58897196/104816079-ab348900-5810-11eb-8e60-395aedc7529a.png)

run this `sudo apt-get install python3-googleapi python3-oauth2client` from [this](https://stackoverflow.com/questions/18267749/importerror-no-module-named-apiclient-discovery#answer-23521799) 

then add your channel id only here a the bottom. its needed nowhere else
![test](https://user-images.githubusercontent.com/58897196/104816263-ee432c00-5811-11eb-8dd2-96b217f7845c.png)

then redirect the ouput in a text file
![redirect_list_text-file](https://user-images.githubusercontent.com/58897196/104816297-2f3b4080-5812-11eb-8906-e7971e08614a.png)

**Comment by s4nyam** [comment]
Thanks for the update!
